### ISSUE TITLE
Add University of Warwick Statistics internship

### ISSUE THREAD

**Issue by prakharrathi25** [vvignesh17/List-of-all-Research-Internship-Program-for-IIT-and-NITs#1]
Can someone add this statistics research internship at the University of Warwick - warwick.ac.uk/fac/sci/statistics/research/internships

Additionally, do you think it will be a good idea to post about some resources for each of these internships? or to make an airtable to save this data?

**Comment by prakharrathi25** [comment]
I would be happy to add this as well.

**Comment by vvignesh17** [comment]
Thanks for providing this information. 
Have updated it in the list.

**Comment by Githubcreating** [comment]
Does anybody know of any available scholarship for pursuing a 10-12-month internship at the University of Warwick or in the UK?
