### ISSUE TITLE
UNDP Geospatial Data Science Internship - Deadline 7 March 2022

### ISSUE THREAD

**Issue by Swetha-Kolluri** [vvignesh17/List-of-all-Research-Internship-Program-for-IIT-and-NITs#2]
Can you please add the UNDP Internship advertised below:

https://jobs.undp.org/cj_view_job.cfm?cur_job_id=105057

https://www.linkedin.com/posts/undp-in-india_hiringnow-applynow-vacancy-activity-6904667750678294528-g5NQ

**Comment by vvignesh17** [comment]
Thanks for providing the information.
